spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #启动数据库历史记录
  #true： activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建。
  #create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）。
  #drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）
  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true
